spring:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    show-sql: true
    open-in-view: false

  datasource:
    hikari:
      username: luman-dev
      password: qwer1234!
      jdbc-url: jdbc:mysql://localhost:3336/chatchat?characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  jackson:
    default-property-inclusion: non_null

jwt:
  secret-key: polarlearn-api-admin-dev-secret-key-lumanlab-v1
  access-token-expired-in: 30m
  refresh-token-expired-in: 1d

logging:
  level:
    org.hibernate.sql: DEBUG
  config: classpath:log/logback-dev-config.xml